import keyMirror from 'keymirror';

export default keyMirror({
    UPDATE_BENCH_INFO: null,
    INIT_TIMELINE: null,
    SET_FILTER: null,
    SET_CURRENT_PAGE: null,
    SHOW_TIMELINE_LOADING_MASK: null,
    HIDE_TIMELINE_LOADING_MASK: null,
    SELECT_BENCH_BY_ID: null,
    SELECT_ACTIVE_TAB: null,
    SELECT_GRAPH: null,
    DESELECT_GRAPH: null,
    NOTIFY: null,
    NEW_BENCH: null,
    SERVER_INFO: null,
    MODIFY_NEW_BENCH: null,
    CLEAN_NEW_BENCH: null,
    CLONE_BENCH: null,
    METRIC_DATA: null,
    METRIC_BATCH_END: null,
    LOG_DATA: null,
    LOG_USER_DATA: null,
    LOG_BATCH_END: null,
    LOG_USER_BATCH_END: null,
    LOG_OVERFLOW: null,
    LOG_USER_OVERFLOW: null,
    UPDATE_LOG_QUERY_DATA: null,
    UPDATE_LOG_QUERY_KIND: null,
    UPDATE_LOG_QUERY_ERRORS: null,
    SUBSCRIBE_METRICS: null
});
